kind: Service
apiVersion: v1
metadata:
  name: kube-state-metrics
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: kube-state-metrics
spec:
  type: NodePort
  selector:
    app: kube-state-metrics
  ports:
  - name: kube-state-metrics
    port: 8080
